[AQW]

[AQW.SERVERS]
artix = '172.65.160.131'
swordhaven = '172.65.207.70'
yokai = '172.65.236.72'
yorumi = '172.65.249.41'
twilly = '172.65.210.123'
safiria = '172.65.249.3'
galanoth = '172.65.249.3'
alteon = '172.65.235.85'
gravelyn = '172.65.235.85'
twig = '172.65.235.85'
espada = '172.65.220.106'
sepulchure = '172.65.220.106'
'sir ver' = '172.65.220.106'

[AQW.PACKETS]
sAct = 'Skill Data'
stu = 'Stat Update'
seia = 'Item Update'
ct = 'Combat'
unknown = 'Unknown'
addItems = 'Add Item'
dropItem = 'Drop Item'
addGoldExp = 'Monster Death'
acceptQuest = 'Accept Quest'
turnIn = 'Turn In Quest'
mtls = 'Status Check'
'aura+p' = 'Aura Passive'
umsg = 'Yellow Combat Message'
updateClass = 'Set Class'
moveToArea = 'Join Map-Lobby'