[ACRONYMS]
AM = 'ARCHMAGE'
AI = 'ARCANA INVOKER'
LR = 'LEGION REVENANT'
AF = 'ARCHFIEND'

['CLASS INFO']

['CLASS INFO'.'LEGION REVENANT']
rotation = ['4', '5', '2', '3']
rotation_type = 'priority'
ability.1 = {cd = 1.5, name = 'Malevolent Burst', mana = 0, key = '1'}
ability.2 = {cd = 6, name = 'Atramentous Shade', mana = 10, key = '2'}
ability.3 = {cd = 6, name = 'Wicked Purgatory', mana = 15, key = '3'}
ability.4 = {cd = 6, name = 'Depraved Empowerment', mana = 15, key = '4'}
ability.5 = {cd = 12, name = 'Anathema', mana = 20, key = '5'}
gcd = 1.8

['CLASS INFO'.'ARCHFIEND']
rotation = ['4', '2', '3']
rotation_type = 'priority'
ability.1 = {cd = 2, name = 'Mark of Death', mana = 0, key = '1'}
ability.2 = {cd = 3, name = 'Fiendish Strike', mana = 15, key = '2'}
ability.3 = {cd = 3, name = 'Consumed by the Abyss', mana = 15, key = '3'}
ability.4 = {cd = 26, name = 'Fiend Frenzy', mana = 25, key = '4'}
ability.5 = {cd = 26, name = 'Abyssal Contract', mana = 25, key = '5'}
gcd = 1.6
