[Arachnomancer.1]
cd = 2.0
name = "Spider Bite"
mana = 0
key = "1"

[Arachnomancer.2]
cd = 6.0
name = "Venom Fangs"
mana = 6
key = "2"

[Arachnomancer.3]
cd = 6.0
name = "Slingshot Web"
mana = 6
key = "3"

[Arachnomancer.4]
cd = 6.0
name = "Leaping Arachnid"
mana = 15
key = "4"

[Arachnomancer.5]
cd = 6.0
name = "Toxic Adrenaline"
mana = 21
key = "5"

["Arcana Invoker".1]
cd = 2.2
name = "Anagenesis"
mana = 0
key = "1"

["Arcana Invoker".2]
cd = 5.0
name = "The Beginning and the End"
mana = 0
key = "2"

["Arcana Invoker".3]
cd = 3.0
name = "Arcana Invocation"
mana = -15
key = "3"

["Arcana Invoker".4]
cd = 3.0
name = "Arcana Revocation"
mana = 40
key = "4"

["Arcana Invoker".5]
cd = 9.0
name = "One With the Cycle"
mana = 0
key = "5"

[ArchFiend.1]
cd = 2.0
name = "Mark of Death"
mana = 0
key = "1"

[ArchFiend.2]
cd = 3.0
name = "Fiendish Strike"
mana = 15
key = "2"

[ArchFiend.3]
cd = 3.0
name = "Consumed by the Abyss"
mana = 15
key = "3"

[ArchFiend.4]
cd = 26.0
name = "Fiend Frenzy"
mana = 25
key = "4"

[ArchFiend.5]
cd = 26.0
name = "Abyssal Contract"
mana = 25
key = "5"

[ArchMage.1]
cd = 1.5
name = "Incantation"
mana = 0
key = "1"

[ArchMage.2]
cd = 4.0
name = "Immolation"
mana = 10
key = "2"

[ArchMage.3]
cd = 2.4
name = "Glacial Impact"
mana = -15
key = "3"

[ArchMage.4]
cd = 4.0
name = "Supernova"
mana = 20
key = "4"

[ArchMage.5]
cd = 3.0
name = "Arcane Sigil"
mana = 0
key = "5"

[ArchPaladin.1]
cd = 2.0
name = "Auto Attack"
mana = 0
key = "1"

[ArchPaladin.2]
cd = 5.0
name = "Commandment"
mana = 10
key = "2"

[ArchPaladin.3]
cd = 10.0
name = "Hymn of Light"
mana = 40
key = "3"

[ArchPaladin.4]
cd = 25.0
name = "Righteous Seal"
mana = 20
key = "4"

[ArchPaladin.5]
cd = 25.0
name = "Sacred Magic: Eden"
mana = 40
key = "5"

["Yami no Ronin".1]
cd = 2.0
name = "Batto"
mana = 0
key = "1"

["Yami no Ronin".2]
cd = 3.0
name = "Tachi"
mana = 3
key = "2"

["Yami no Ronin".3]
cd = 14.0
name = "Yami no Maku"
mana = 20
key = "3"

["Yami no Ronin".4]
cd = 3.0
name = "Kettou"
mana = 3
key = "4"

["Yami no Ronin".5]
cd = 6.0
name = "Jigen Kogeki"
mana = 20
key = "5"

["Exalted Soul Cleaver".1]
cd = 3.0
name = "Soul Breaker"
mana = 0
key = "1"

["Exalted Soul Cleaver".2]
cd = 6.0
name = "Soul Rend"
mana = 15
key = "2"

["Exalted Soul Cleaver".3]
cd = 6.0
name = "Soul Leech"
mana = 30
key = "3"

["Exalted Soul Cleaver".4]
cd = 12.0
name = "Soul Pact"
mana = 50
key = "4"

["Exalted Soul Cleaver".5]
cd = 3.0
name = "Blood Price"
mana = 0
key = "5"

["Dragon of Time".1]
cd = 2.0
name = "Rend Time"
mana = 0
key = "1"

["Dragon of Time".2]
cd = 6.0
name = "Confluence of Fates"
mana = 0
key = "2"

["Dragon of Time".3]
cd = 3.0
name = "Dragon's Will"
mana = 15
key = "3"

["Dragon of Time".4]
cd = 6.0
name = "Burning Fates"
mana = 0
key = "4"

["Dragon of Time".5]
cd = 8.0
name = "Hero's Heartbeat"
mana = 25
key = "5"

["Chaos Avenger".1]
cd = 3.0
name = "Chaos Greatsword"
mana = -60
key = "1"

["Chaos Avenger".2]
cd = 6.0
name = "Chaos Siphon"
mana = 50
key = "2"

["Chaos Avenger".3]
cd = 15.0
name = "Flux"
mana = 50
key = "3"

["Chaos Avenger".4]
cd = 6.0
name = "Chaos Bulwark"
mana = 50
key = "4"

["Chaos Avenger".5]
cd = 35.0
name = "Fury Unleashed"
mana = 50
key = "5"

["Chrono ShadowHunter".1]
cd = 0.2
name = "Fire!"
mana = 15
key = "1"

["Chrono ShadowHunter".2]
cd = 6.0
name = "Reload"
mana = -1000
key = "2"

["Chrono ShadowHunter".3]
cd = 3.0
name = "Tracer Rounds"
mana = 5
key = "3"

["Chrono ShadowHunter".4]
cd = 1.5
name = "FMJ Rounds"
mana = 5
key = "4"

["Chrono ShadowHunter".5]
cd = 6.0
name = "Silver Bullet"
mana = 0
key = "5"

["Neo Metal Necro".1]
cd = 2.0
name = "Auto Attack"
mana = 0
key = "1"

["Neo Metal Necro".2]
cd = 6.0
name = "Shocking Soundwave"
mana = 10
key = "2"

["Neo Metal Necro".3]
cd = 8.0
name = "Mental Breakdown"
mana = 15
key = "3"

["Neo Metal Necro".4]
cd = 6.0
name = "Subsuming Scream"
mana = 10
key = "4"

["Neo Metal Necro".5]
cd = 3.0
name = "Enraging Pain"
mana = 0
key = "5"
