['SUPPLIES TO SPIN THE WHEEL OF CHANCE']
quest_id = -9999

['WHEEL OF CHANCE'.REQUIREMENTS]
67266 = 1

['SUPPLIES TO SPIN THE WHEEL OF CHANCE'.CAP]
67266 = 1

['SWINDLES RETURN POLICY']
quest_id = -9999

['SWINDLES RETURN POLICY'.REQUIREMENTS]
-1 = 1
-2 = 1
-3 = 1
4749 = 1
4767 = 1
-4 = 1

['SWINDLES RETURN POLICY'.CAP]
-1 = 1
-2 = 1
-3 = 1
4749 = 1
4767 = 1
-4 = 13

['OBSIDIAN MINING']
quest_id = -9999

['OBSIDIAN MINING'.REQUIREMENTS]
16408 = 10

['OBSIDIAN MINING'.CAP]
16408 = 100

['UNDEAD CHAMPION RECRUITMENT']
quest_id = -9999

['UNDEAD CHAMPION RECRUITMENT'.REQUIREMENTS]
33883 = 6

['UNDEAD CHAMPION RECRUITMENT'.CAP]
33883 = 6

['TEST']
quest_id = -9999

['TEST'.REQUIREMENTS]
-9999 = 9999

['TEST'.CAP]
-9999 = 9999
