['SUPPLIES TO SPIN THE WHEEL OF CHANCE']
67266 = [1, 13]

['SWINDLES RETURN POLICY']
-1 = [1, 1]
-2 = [1, 1]
-3 = [1, 1]
4749 = [1, 1]
4767 = [1, 1]
-4 = [1, 13]

['OBSIDIAN MINING']
16408 = [10, 100]

['UNDEAD CHAMPION RECRUITMENT']
33883 = [6, 6]

['TEST']
-9999 = [9999, 9999]
