[33883]
name = 'Dreadrock Enemy Recruited'
type = 'Temporary Item'
monsters = ['']

[8940]
name = 'Treasure Chest'
type = 'Misc. Item'

[69879]
name = "FA'S GAMER FUEL"
type = 'Misc. Item'

[69842]
name = "Fa's Bean Bag"
type = 'House Item'

[69844]
name = "Mi's Bean Bag"
type = 'House Item'

[69845]
name = "Re's Bean Bags"
type = 'House Item'




