[47390]
name = "Mysterious Vanta Hood"
count = 22

[59907]
name = "Underworld Scourge's Hair"
count = 9

[59904]
name = "Underworld Scourge's Hood"
count = 8

[59906]
name = "Underworld Scourge's Mask + Locks"
count = 10

[59908]
name = "Underworld Scourge's Mask"
count = 8

[47392]
name = "Torn Vanta Scarf"
count = 20

[59726]
name = "Legion Operative Skull"
count = 10

[59912]
name = "Underworld Scourge's Rune Cloak"
count = 11

[47391]
name = "Torn Vanta Hood"
count = 28

[59905]
name = "Underworld Scourge's Locks"
count = 16

[59909]
name = "Underworld Souls Rune"
count = 13

[59913]
name = "Underworld Scourge's Cloak"
count = 7

[59911]
name = "Underworld Scourge's Crescent"
count = 10

[59903]
name = "Underworld Scourge's Armet"
count = 8

[8940]
name = "Treasure Chest"
count = 6

[59910]
name = "Underworld Scourge's Scarf"
count = 8
